.TH XBindKeys_Show 1 "Thu 08 Jan 2004"
.UC 1
.SH "NAME"
xbindkeys_show \- a program to show the grabbing keys used in xbindkeys
.SH "SYNOPSIS"
\fBxbindkeys_show\fP
.br
.SH "DESCRIPTION"
\fIXbindKeys_Show\fP is a program that show the grabbing keys used in
xbindkeys.

.SH "COMMAND LINE OPTIONS"
Available command line options are as follows:
.TP
\fB-f, --file\fP
Use an alternative rc file
.TP
\fB-h, --help\fP
Short help on options plus version/author info.

.LP
.SH "BUGS"
If you find a bug, please send a mail to <hocwp@free.fr>
.LP
.SH "HOMEPAGE"
.nf
http://hocwp.free.fr/xbindkeys
.fi

.LP
.SH "AUTHOR"
Philippe Brochard <hocwp@free.fr>

.LP
.SH "SEE ALSO"
.nf

\fBxbindkeys\fP
    A grabbing keys program for X.
\fBxmodmap(1x)\fP
    Utility for modifying keymap & button mappings in X.
\fBxev(1x)\fP
    Print contents of X events.
\fB/usr/include/X11/keysymdef.h\fP
    X11 KeySym definitions.

